### ISSUE TITLE
Ошибка чтения "dat:/Bm.BGO.bg00" после недавнего обновления

### ISSUE THREAD

**Issue by Kakadu** [ObKo/OpenSR#15]
Что надо сделать с ресурсами игры, чтобы оно начало читаться?

**Comment by Kakadu** [comment]
Кажется,  это связано со 'startup.qs'. Можете сказать пару слов, как оно должно работать?

P.S. разобрался как вернуть назад

**Comment by ObKo** [comment]
Да, теперь нужны файлы *.dat из оригинальной игры (революция, без модов). Их нужно декодировать (tools/DATTools) и сложить в папку с ресурсами.

**Comment by ObKo** [comment]
Точнее, не Революция, а Перезагрузка. Последнее издание от elemental games,  короче. В Революции поменяли ключи, а в HD вообще шифруют по другому.

Также в DATTools есть конвертер .dat в формат JSON, если кто хочет посмотреть, что внутри. Ну и конвертер обратно - можно заменять данные в оригинале.

**Comment by Kakadu** [comment]
@ObKo Я раньше руками распаковывал pkg файлы. Хз из какой версии игры они. 

Они не подойдут?

**Comment by ObKo** [comment]
pkg файлы не менялись, вроде, только добавлялись в аддонах. dat файлы были в каждом релизе разные, они зашифрованы, с разным ключём шифрования, известен ключ только для релиза Перезагрузка. dat файлы лежат в директории cfg/ установленной игры. Пока нужны только main.dat, rus.dat и CacheData.dat и их нужно расшифровать:

    opensr-dat-convert d main.dat ~/OpenSR/data/main.dat
    opensr-dat-convert d rus.dat ~/OpenSR/data/rus.dat
    opensr-dat-convert hd CacheData.dat ~/OpenSR/data/CacheData.dat

**Comment by Kakadu** [comment]
````
➜  OpenSR git:(rework3) ✗ tools/DATTools/opensr-dat-convert d ../OpenSRData/CacheData.dat ./data/main.dat
CRC Error
➜  OpenSR git:(rework3) ✗ tools/DATTools/opensr-dat-convert d ../OpenSRData/Rus.dat ./data/rus.dat
➜  OpenSR git:(rework3) ✗ tools/DATTools/opensr-dat-convert hd ../OpenSRData/CacheData.dat ./data/CacheData.dat

````

Соответственно из-за ошибки CRC полученный main.dat надо удалять, потому что игра зависает на чтении. А без файла нет и астероидов. Что может быть не так? файлы брал из файла  `Space Rangers 2 - Reload + Space Rangers [RUS].nrg`

**Comment by ObKo** [comment]
Для CacheData нужно не d, а hd - CacheData.dat особый файл с немного другим форматом.

**Comment by Kakadu** [comment]
@ObKo  А у меня не оно? 

P.S. аааааааааааа, понял

P.P.S. Заработало.
