### ISSUE TITLE
Всё плохо с созданием объектов из скрипта.

### ISSUE THREAD

**Issue by Kakadu** [ObKo/OpenSR#17]
Всё сломалось в коммите https://github.com/ObKo/OpenSR/commit/104f568f8a19e16103f64f2fc2e5a92fbfdcda64

Опытным путём установил, что из JS не дергаются методы названный `newClassName` но всё нормально когда просто `ClassName`. Кажется c типом результата это не связано.

Временно откатил изменения в коммите https://github.com/Kakadu/OpenSR/commit/ad238fe01a97637109f8f91de3ed108be63cf1ef

**Comment by ObKo** [comment]
Подожди. Попробуй удалить всю сборку (ну или хотя бы World/moc_WorldBindings.cpp World/moc_WorldManager.cpp) и собрать заново - там moc странно себя ведет, из-за того, что раньше использовались макросы.

**Comment by Kakadu** [comment]
Что-то я пробовал вчера клинить, но не получалось. Надо было делать `rm -fr`. Сейчас всё починилось
