### ISSUE TITLE
Python imports error.

### ISSUE THREAD

**Issue by Kaffeine** [ObKo/OpenSR#4]
When I try to run opensr binary, I get follow console output:
[--] Python path: 
[EE] ImportError: No module named OpenSR.Engine

I think that problem may be related to _Engine.so, which is not processed at install.
I'm not familiar with python and can't fix it myself.

**Comment by ObKo** [comment]
Place (or symlink) _Engine.so to python/OpenSR/Engine/ dir. Then create ~/.config/OpenSR/OpenSR.conf:

```
[data]
mainDataDir=<path_to_"data"_dir>
[engine]
pythonPath=<path_to_"python"_dir>
```

Do not expect much from this project. There only engine, no game at all. Furthermore, everything is broken for now due to problem with python objects lifetime. I've no time to fix it.
